"""pgn-file table

Revision ID: 9c507e223783
Revises: 
Create Date: 2019-10-06 17:11:32.567268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c507e223783'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pgn_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pgn', sa.String(), nullable=True),
    sa.Column('white_player', sa.String(length=64), nullable=True),
    sa.Column('black_player', sa.String(length=64), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pgn_file_black_player'), 'pgn_file', ['black_player'], unique=False)
    op.create_index(op.f('ix_pgn_file_date'), 'pgn_file', ['date'], unique=False)
    op.create_index(op.f('ix_pgn_file_pgn'), 'pgn_file', ['pgn'], unique=True)
    op.create_index(op.f('ix_pgn_file_white_player'), 'pgn_file', ['white_player'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pgn_file_white_player'), table_name='pgn_file')
    op.drop_index(op.f('ix_pgn_file_pgn'), table_name='pgn_file')
    op.drop_index(op.f('ix_pgn_file_date'), table_name='pgn_file')
    op.drop_index(op.f('ix_pgn_file_black_player'), table_name='pgn_file')
    op.drop_table('pgn_file')
    # ### end Alembic commands ###
