"""Game.is_from_user column

Revision ID: efdeea76aa8f
Revises: 3b10f3899fb6
Create Date: 2019-10-08 11:01:47.171426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efdeea76aa8f'
down_revision = '3b10f3899fb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('is_from_user', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'is_from_user')
    # ### end Alembic commands ###
